---
- name: Provision DigitalOcean Droplet Environment
  hosts: localhost
  connection: local
  become: true

  vars:
    repo_url: "https://github.com/GistWiz/cli.git"

  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.package:
        name:
          - git
          - curl
          - tree
          - unzip
          - vim
        state: present

    - name: Download Redis Stack Server (https://download.redis.io/releases)
      get_url:
        url: "https://packages.redis.io/redis-stack/redis-stack-server-7.4.0-v1.rhel9.x86_64.tar.gz"
        dest: /tmp/redis-stack-server.tar.gz
        mode: '0644'

    - name: Create destination directory for Redis Stack
      file:
        path: /opt/redis
        state: directory
        mode: '0755'

    - name: Extract Redis Stack Server
      unarchive:
        src: /tmp/redis.gz
        dest: /opt/redis
        remote_src: yes
        extra_opts:
          - --strip-components=2

    - name: Ensure /opt/redis/bin is in PATH for root user
      lineinfile:
        path: /root/.bashrc
        line: 'export PATH=$PATH:/opt/redis/bin'
        create: yes
        state: present

    - name: Configure Redis Stack service
      copy:
        dest: /etc/systemd/system/redis.service
        content: |
          [Unit]
          Description=Redis Stack Server
          After=network.target

          [Service]
          ExecStart=/opt/redis/bin/redis-stack-server /opt/redis/etc/redis.conf
          Restart=always
          User=root
          Environment="PATH=/opt/redis/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd to apply new service
      systemd:
        daemon_reload: yes

    - name: Enable and start Redis Stack service
      systemd:
        name: redis-stack.service
        enabled: true
        state: started

    - name: Install Bun JavaScript runtime
      ansible.builtin.shell: |
        export HOME=/root
        curl -fsSL https://bun.sh/install | bash
        echo 'export PATH="/root/.bun/bin:$PATH"' >> /root/.bashrc
        source /root/.bashrc
        which bun
        bun --version
      args:
        executable: /bin/bash
      register: bun_install_output
      changed_when: "'bun was installed successfully' in bun_install_output.stdout"

    - name: Verify Bun installation
      ansible.builtin.shell: |
        source /root/.bashrc
        which bun && bun --version
      args:
        executable: /bin/bash
      register: bun_verify_output
      failed_when: "'command not found' in bun_verify_output.stderr"

    - name: Clone the application repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: /opt/gistwiz
        version: "{{ branch | default('main') }}"
        force: yes

    - name: Install application dependencies using Bun
      ansible.builtin.shell: |
        source /root/.bashrc
        cd /opt/gistwiz
        bun install
      args:
        executable: /bin/bash

    - name: Setup GistWiz Environment Variables
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "QUEUE_NAME_GISTS=gists"

    - name: Create a systemd service for the application
      ansible.builtin.copy:
        dest: /etc/systemd/system/gistwiz.service
        content: |
          [Unit]
          Description=GistWiz Server
          After=network.target

          [Service]
          ExecStart=/bin/bash -c '/root/.bun/bin/bun run src/cli.ts serve'
          WorkingDirectory=/opt/gistwiz
          Restart=always
          User=root
          EnvironmentFile=/etc/environment

          [Install]
          WantedBy=multi-user.target

    - name: Create a systemd service for the GistWiz worker
      ansible.builtin.copy:
        dest: /etc/systemd/system/gistwiz-worker.service
        content: |
          [Unit]
          Description=GistWiz Worker
          After=network.target

          [Service]
          ExecStart=/bin/bash -c '/root/.bun/bin/bun run src/cli.ts worker'
          WorkingDirectory=/opt/gistwiz
          Restart=always
          User=root
          EnvironmentFile=/etc/environment

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd and start services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - gistwiz.service
        - gistwiz-worker.service

    - name: Tag provision completion
      debug:
        msg: "Provisioning complete. GistWiz services are up and running with Bun configured!"