---
- name: Provision DigitalOcean Droplet Environment
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Update and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Ensure required packages are installed
      ansible.builtin.package:
        name:
          - git
          - curl
          - unzip
        state: present

    - name: Clone the application repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: /opt/application
        version: "{{ branch | default('main') }}"
        force: yes

    - name: Ensure application directory exists
      ansible.builtin.file:
        path: /opt/application
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Install Bun JavaScript runtime
      ansible.builtin.shell: |
        curl -fsSL https://bun.sh/install | bash
        export PATH="$HOME/.bun/bin:$PATH"
      args:
        executable: /bin/bash

    - name: Install application dependencies using Bun
      ansible.builtin.shell: |
        export PATH="$HOME/.bun/bin:$PATH"
        cd /opt/application
        bun install
      args:
        executable: /bin/bash

    - name: Create a systemd service for the application
      ansible.builtin.copy:
        dest: /etc/systemd/system/application.service
        content: |
          [Unit]
          Description=Application Service
          After=network.target

          [Service]
          ExecStart=/bin/bash -c '/root/.bun/bin/bun run src/cli.ts serve'
          WorkingDirectory=/opt/application
          Restart=always
          User=root
          Environment="PATH=/root/.bun/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

          [Install]
          WantedBy=multi-user.target
    - name: Reload systemd and start the application service
      ansible.builtin.systemd:
        name: application.service
        enabled: true
        state: started

    - name: Tag provision completion
      debug:
        msg: "Provisioning complete. Application service is up and running!"